### PR TITLE
docs(frontend): Guia Markdown resolve https://github.com/orgs/eoscost…

### LINKED ISSUE #164: Guia Markdown
As a new developer joining EOS Costa Rica I would like to see a quick quide to markdown with links to useful content (eg: cheatsheets in order to get started faster with markdown.

**Acceptance Criteria:** 
- Let's include under the [tutorials section](https://guide.eoscostarica.io/docs/tutorials)

### PR DESCRIPTION
**Pull request by steph222**
…arica/projects/3#card-52252436

### GH Issue 

Resolves #164  

### Steps to test
1. Go to Guía Marckdown inside of Tutoriales tag
2. Check content is right

#### CheckList
- [ ] Include under the tutorials section

### CODE REVIEW

**Comment by xavier506** [comment]
👍  Excellent work!

**Review by xavier506 — APPROVED** [review]
💯

**Review by leisterfrancisco — APPROVED** [review]
Good work 👍

**Review by edgarEOS — APPROVED** [review]
Well Done!

**Pull request merged**
