### PR TITLE
update(contributos): Add new contributors

### LINKED ISSUE #174: Actualizar contribuidores
Actualizar la tabla de contribuidores segun especificado en este enlace 

https://github.com/all-contributors/all-contributors

### PR DESCRIPTION
**Pull request by Edgar097**
### GH Issue
Resolves #174 
# 

### Steps to test
1. Open README
1. Check the contributors list

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

### CODE REVIEW

**Review by xavier506 — CHANGES_REQUESTED** [review]
Lets add Jean Vega , Angelo Castro , and Luis Diego Rojas to the contributors

**Review by leisterfrancisco — APPROVED** [review]
Good work :+1:

**Comment by Edgar097** [comment]
New contributors added , we can merge this PR

**Review by steph222 — APPROVED** [review]
Good 👍

**Review by xavier506 — APPROVED** [review]
LGTM

**Pull request merged**
